/** Human-readable labels for CaseFile / SubjectProfile subject_type values. */

const LABELS = {
  senator: "U.S. Senator",
  house_member: "U.S. House member",
  executive: "Executive branch",
  vp: "Vice President",
  federal_judge_scotus: "Supreme Court justice",
  federal_judge_circuit: "Circuit judge",
  federal_judge_district: "District judge",
  federal_judge_magistrate: "Magistrate judge",
  federal_judge_bankruptcy: "Bankruptcy judge",
  administrative_law_judge: "Administrative law judge",
  state_governor: "Governor",
  state_legislator: "State legislator",
  state_judge: "State judge",
  state_ag: "State attorney general",
  state_sos: "Secretary of state",
  mayor: "Mayor",
  city_council: "City council",
  city_executive: "City executive",
  county_sheriff: "County sheriff",
  sheriff: "Sheriff",
  county_prosecutor: "County prosecutor",
  district_attorney: "District attorney",
  state_attorney_general: "Attorney general",
  public_defender_chief: "Public defender",
  county_clerk: "County clerk",
  county_assessor: "County assessor",
  school_board: "School board",
  school_board_member: "School board member",
  police_commissioner: "Police commissioner",
  police_chief: "Police chief",
  federal_marshal: "Federal marshal",
  zoning_board_member: "Zoning board",
  planning_commission_member: "Planning commission",
  historic_preservation_board_member: "Historic preservation board",
  utility_board_member: "Utility board",
  water_board_member: "Water board",
  transit_board_member: "Transit board",
  port_authority_commissioner: "Port authority",
  airport_authority_member: "Airport authority",
  school_superintendent: "Superintendent",
  university_regent: "Regent",
  public_health_officer: "Public health officer",
  fire_commissioner: "Fire commissioner",
  emergency_management_director: "Emergency management",
  parole_board_member: "Parole board",
  corrections_commissioner: "Corrections",
  juvenile_court_officer: "Juvenile court",
  city_comptroller: "Comptroller",
  state_treasurer: "State treasurer",
  inspector_general: "Inspector general",
  auditor_general: "Auditor general",
  liquor_control_board_member: "Liquor control board",
  gaming_commission_member: "Gaming commission",
  professional_licensing_board_member: "Professional licensing board",
  regional_planning_authority_member: "Regional planning",
  special_district_board_member: "Special district board",
  flood_control_district_member: "Flood control district",
  public_official: "Public official",
  corporation: "Corporation",
  organization: "Organization",
};

export const JUDICIAL_SUBJECT_TYPES = new Set([
  "federal_judge_scotus",
  "federal_judge_circuit",
  "federal_judge_district",
  "federal_judge_magistrate",
  "federal_judge_bankruptcy",
  "administrative_law_judge",
  "state_judge",
]);

export function subjectTypeLabel(type) {
  if (!type) return "Official";
  return LABELS[type] || type.replace(/_/g, " ");
}
