"""Deterministic JSON-shaped dicts for JCS signing (case + evidence)."""
from __future__ import annotations

import json
from datetime import date, datetime, timezone
from typing import TYPE_CHECKING, Any

from core.datetime_utils import coerce_utc
from models import CaseFile, EvidenceEntry

if TYPE_CHECKING:
    from sqlalchemy.orm import Session

METHODOLOGY_NOTE_VERSION = "1.1"
METHODOLOGY_LEGAL_LIABILITY_NOTE = (
    "Profiles of sitting judicial officers include allegations tagged by epistemic level. "
    "Findings tagged ALLEGED represent formal complaints or legal allegations and have not been adjudicated. "
    "Findings tagged CONTEXTUAL represent public discourse and have not been independently verified. "
    "All findings link directly to primary sources."
)

METHODOLOGY_NOTE_TEXT = (
    """How this report works

What a signal is:
A signal documents a public-record connection between a financial contribution to an official's campaign committee and a vote cast by that official within a configurable time window. It does not assert that the donation influenced the vote.

Evidence tiers:
• Documented — FEC donation record + Senate roll call vote within the proximity window
• Corroborated — Documented + one additional public-record indicator (active lobbying registration OR jurisdictional industry match)
• Multi-source — Documented + two or more additional public-record indicators

What is not checked in this run:
• Regulations.gov comment dockets — credential not configured
• GovInfo congressional hearing witnesses — credential not configured

Confirmation standard:
A signal reaches "confirmed" status when identity is resolved, temporal direction is verified, and at least two independent public-record indicators are present. No signals in this run met that standard because two evidence channels were unavailable.

Source data:
• FEC: api.open.fec.gov — Federal Election Commission public disclosure
• Senate votes: senate.gov LIS XML — official Senate roll call record
• LDA: lda.gov — lobbying disclosure (API + public filing views; legacy lda.senate.gov URLs 404)
• All sources are public government records

"""
    + "\n"
    + METHODOLOGY_LEGAL_LIABILITY_NOTE
    + "\n\n"
    + "This report was generated by Open Case and cryptographically signed at the time of generation. "
    "The signature covers all signals, evidence references, source statuses, and this methodology note."
)


def _dt_iso(v: Any) -> str | None:
    """UTC `YYYY-MM-DDTHH:MM:SSZ` so SQLite round-trips match what is signed."""
    if v is None:
        return None
    if isinstance(v, date) and not isinstance(v, datetime):
        return v.isoformat()
    if isinstance(v, datetime):
        cu = coerce_utc(v)
        if cu is None:
            return None
        return cu.strftime("%Y-%m-%dT%H:%M:%SZ")
    return str(v)


def epistemic_distribution_from_entries(entries: list[EvidenceEntry]) -> dict[str, int]:
    from services.epistemic_classifier import ALL_LEVELS

    c = {k: 0 for k in ALL_LEVELS}
    for e in entries:
        lev = (getattr(e, "epistemic_level", None) or "REPORTED").strip()
        if lev in c:
            c[lev] += 1
        else:
            c["REPORTED"] += 1
    return c


def case_semantic_dict(c: CaseFile) -> dict[str, Any]:
    """Fields that define the case record; excludes counters, signing metadata."""
    base: dict[str, Any] = {
        "id": str(c.id),
        "slug": c.slug,
        "title": c.title,
        "subject_name": c.subject_name,
        "subject_type": c.subject_type,
        "jurisdiction": c.jurisdiction,
        "status": c.status,
        "created_at": _dt_iso(c.created_at),
        "created_by": c.created_by,
        "summary": c.summary,
        "pickup_note": c.pickup_note or "",
        "is_public": c.is_public,
    }
    lss = getattr(c, "last_source_statuses", None)
    if lss:
        base["last_source_statuses"] = lss
    gl = getattr(c, "government_level", None)
    br = getattr(c, "branch", None)
    pc = getattr(c, "pilot_cohort", None)
    if gl:
        base["government_level"] = gl
    if br:
        base["branch"] = br
    if pc:
        base["pilot_cohort"] = pc
    return base


def evidence_semantic_dict(e: EvidenceEntry) -> dict[str, Any]:
    d: dict[str, Any] = {
        "id": str(e.id),
        "case_file_id": str(e.case_file_id),
        "entry_type": e.entry_type,
        "title": e.title,
        "body": e.body,
        "source_url": e.source_url or "",
        "source_name": e.source_name or "",
        "date_of_event": e.date_of_event.isoformat() if e.date_of_event else None,
        "entered_at": _dt_iso(e.entered_at),
        "entered_by": e.entered_by,
        "confidence": e.confidence,
        "is_absence": e.is_absence,
        "flagged_for_review": e.flagged_for_review,
        "epistemic_level": getattr(e, "epistemic_level", None) or "REPORTED",
        "source_type": getattr(e, "source_type", None) or "other",
        "classification_basis": getattr(e, "classification_basis", None) or "",
        "review_status": getattr(e, "review_status", None) or "pending",
        "claim_status": getattr(e, "claim_status", None) or "active",
    }
    if e.amount is not None:
        d["amount"] = e.amount
    if e.matched_name:
        d["matched_name"] = e.matched_name
    if getattr(e, "evidence_hash", None):
        d["evidence_hash"] = e.evidence_hash
    if getattr(e, "disambiguation_note", None):
        d["disambiguation_note"] = e.disambiguation_note
    if getattr(e, "disambiguation_by", None):
        d["disambiguation_by"] = e.disambiguation_by
    if getattr(e, "disambiguation_at", None) and e.disambiguation_at:
        d["disambiguation_at"] = _dt_iso(e.disambiguation_at)
    if getattr(e, "jurisdictional_match", None) is not None:
        d["jurisdictional_match"] = bool(e.jurisdictional_match)
    mc = getattr(e, "matched_committees", None)
    if mc:
        d["matched_committees"] = mc
    return d


def sign_evidence_entry(entry: EvidenceEntry) -> None:
    from signing import pack_signed_hash, sign_payload

    sem = evidence_semantic_dict(entry)
    signed = sign_payload(sem)
    entry.signed_hash = pack_signed_hash(signed["content_hash"], signed["signature"])


def legacy_v1_full_case_signing_payload(
    case: CaseFile, entries: list[EvidenceEntry]
) -> dict[str, Any]:
    """Pre–Phase 9B bundle: no pattern_alerts key (used to verify older seals)."""
    ordered = sorted(entries, key=lambda x: str(x.id))
    return {
        "schema_version": "open-case-full-1",
        "case": case_semantic_dict(case),
        "evidence": [evidence_semantic_dict(x) for x in ordered],
    }


def full_case_signing_payload(
    case: CaseFile,
    entries: list[EvidenceEntry],
    pattern_alerts: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    ordered = sorted(entries, key=lambda x: str(x.id))
    pal = pattern_alerts if pattern_alerts is not None else []
    return {
        "schema_version": "open-case-full-2",
        "case": case_semantic_dict(case),
        "evidence": [evidence_semantic_dict(x) for x in ordered],
        "pattern_alerts": pal,
    }


def seal_case_bundle_v3(
    case: CaseFile,
    entries: list[EvidenceEntry],
    pattern_alerts: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Legacy digest (open-case-full-3) for verifying older seals without case_signals."""
    ordered = sorted(entries, key=lambda x: str(x.id))
    pal = pattern_alerts if pattern_alerts is not None else []
    return {
        "schema_version": "open-case-full-3",
        "case": case_semantic_dict(case),
        "evidence": [evidence_semantic_dict(x) for x in ordered],
        "pattern_alerts": pal,
        "methodology_note": METHODOLOGY_NOTE_TEXT,
        "methodology_note_version": METHODOLOGY_NOTE_VERSION,
    }


def seal_case_bundle(
    case: CaseFile,
    entries: list[EvidenceEntry],
    pattern_alerts: list[dict[str, Any]] | None = None,
    case_signals: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Canonical case seal including methodology and per-signal proportionality (open-case-full-4)."""
    ordered = sorted(entries, key=lambda x: str(x.id))
    pal = pattern_alerts if pattern_alerts is not None else []
    cs = case_signals if case_signals is not None else []
    return {
        "schema_version": "open-case-full-4",
        "case": case_semantic_dict(case),
        "evidence": [evidence_semantic_dict(x) for x in ordered],
        "pattern_alerts": pal,
        "case_signals": cs,
        "epistemic_distribution": epistemic_distribution_from_entries(ordered),
        "methodology_note": METHODOLOGY_NOTE_TEXT,
        "methodology_note_version": METHODOLOGY_NOTE_VERSION,
    }


def verify_case_file_seal(
    case: CaseFile,
    entries: list[EvidenceEntry],
    db: "Session | None",
) -> dict[str, Any]:
    """Verify case.signed_hash: prefer embedded canonical payload; fall back to legacy shapes."""
    from signing import unpack_signed_hash, verify_signed_hash_string

    packed = (case.signed_hash or "").strip()
    if not packed:
        return {"ok": False, "reasons": ["empty signed_hash"]}
    try:
        data = unpack_signed_hash(packed)
    except json.JSONDecodeError:
        return {"ok": False, "reasons": ["invalid signed_hash json"]}
    if isinstance(data.get("payload"), dict):
        return verify_signed_hash_string(packed, None)
    legacy = legacy_v1_full_case_signing_payload(case, entries)
    r = verify_signed_hash_string(packed, legacy)
    if r["ok"]:
        return r
    if db is not None:
        from engines.pattern_engine import pattern_alerts_for_signing, run_pattern_engine
        from services.proportionality import case_signals_for_signing

        pal = pattern_alerts_for_signing(run_pattern_engine(db))
        case_sig = case_signals_for_signing(db, case.id)
        for candidate in (
            seal_case_bundle(case, entries, pal, case_sig),
            seal_case_bundle(case, entries, [], case_sig),
            seal_case_bundle_v3(case, entries, pal),
            seal_case_bundle_v3(case, entries, []),
            full_case_signing_payload(case, entries, pal),
            full_case_signing_payload(case, entries, []),
        ):
            r2 = verify_signed_hash_string(packed, candidate)
            if r2["ok"]:
                return r2
    return r


def apply_case_file_signature(
    case: CaseFile,
    entries: list[EvidenceEntry],
    *,
    db: "Session | None" = None,
) -> None:
    """Update case.signed_hash / last_signed_at from full case + evidence canonical payload."""
    from signing import pack_signed_hash, sign_payload

    pattern_payload: list[dict[str, Any]] = []
    if db is not None:
        from engines.pattern_engine import (
            pattern_alerts_for_signing,
            run_pattern_engine,
            sync_pattern_alert_records,
        )

        raw = run_pattern_engine(db)
        pattern_payload = pattern_alerts_for_signing(raw)
        sync_pattern_alert_records(db, raw)

    from services.proportionality import case_signals_for_signing

    case_sig = case_signals_for_signing(db, case.id) if db is not None else []
    payload = seal_case_bundle(case, entries, pattern_payload, case_sig)
    signed = sign_payload(payload)
    case.signed_hash = pack_signed_hash(
        signed["content_hash"], signed["signature"], payload
    )
    case.last_signed_at = datetime.now(timezone.utc)
