"""phase_1_2_initial_schema

Revision ID: fdf38be85272
Revises: 
Create Date: 2026-04-02 00:22:39.035513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdf38be85272'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adapter_cache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('adapter_name', sa.String(length=128), nullable=False),
    sa.Column('query_hash', sa.String(length=64), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ttl_hours', sa.Integer(), nullable=False),
    sa.Column('query_string', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adapter_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adapter_cache_adapter_name'), ['adapter_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_adapter_cache_query_hash'), ['query_hash'], unique=False)

    op.create_table('case_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('subject_name', sa.String(length=512), nullable=False),
    sa.Column('subject_type', sa.String(length=64), nullable=False),
    sa.Column('jurisdiction', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=256), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('pickup_note', sa.Text(), nullable=False),
    sa.Column('signed_hash', sa.Text(), nullable=False),
    sa.Column('last_signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_files_slug'), ['slug'], unique=True)

    op.create_table('investigators',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('handle', sa.String(length=256), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('credibility_score', sa.Integer(), nullable=False),
    sa.Column('cases_opened', sa.Integer(), nullable=False),
    sa.Column('entries_contributed', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_anchor', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investigators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investigators_handle'), ['handle'], unique=True)

    op.create_table('case_contributors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_file_id', sa.Uuid(), nullable=False),
    sa.Column('investigator_handle', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_file_id'], ['case_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_file_id', 'investigator_handle', name='uq_case_investigator')
    )
    with op.batch_alter_table('case_contributors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_contributors_case_file_id'), ['case_file_id'], unique=False)

    op.create_table('case_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_file_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_number', sa.Integer(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('taken_by', sa.String(length=256), nullable=False),
    sa.Column('entry_count', sa.Integer(), nullable=False),
    sa.Column('signed_hash', sa.Text(), nullable=False),
    sa.Column('share_url', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['case_file_id'], ['case_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_snapshots_case_file_id'), ['case_file_id'], unique=False)

    op.create_table('evidence_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_file_id', sa.Uuid(), nullable=False),
    sa.Column('entry_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=512), nullable=False),
    sa.Column('date_of_event', sa.Date(), nullable=True),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entered_by', sa.String(length=256), nullable=False),
    sa.Column('signed_hash', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=32), nullable=False),
    sa.Column('is_absence', sa.Boolean(), nullable=False),
    sa.Column('flagged_for_review', sa.Boolean(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('matched_name', sa.String(length=512), nullable=True),
    sa.Column('raw_data_json', sa.Text(), nullable=False),
    sa.Column('evidence_hash', sa.String(length=64), nullable=True),
    sa.Column('disambiguation_note', sa.Text(), nullable=True),
    sa.Column('disambiguation_by', sa.String(length=256), nullable=True),
    sa.Column('disambiguation_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_file_id'], ['case_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_entries_case_file_id'), ['case_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_entries_evidence_hash'), ['evidence_hash'], unique=False)

    op.create_table('signals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_file_id', sa.Uuid(), nullable=False),
    sa.Column('signal_type', sa.String(length=64), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_ids', sa.Text(), nullable=False),
    sa.Column('actor_a', sa.String(length=512), nullable=True),
    sa.Column('actor_b', sa.String(length=512), nullable=True),
    sa.Column('event_date_a', sa.String(length=32), nullable=True),
    sa.Column('event_date_b', sa.String(length=32), nullable=True),
    sa.Column('days_between', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by', sa.String(length=256), nullable=True),
    sa.Column('dismissed_by', sa.String(length=256), nullable=True),
    sa.Column('dismissed_reason', sa.Text(), nullable=True),
    sa.Column('weight_breakdown', sa.Text(), nullable=True),
    sa.Column('weight_explanation', sa.Text(), nullable=True),
    sa.Column('exposure_state', sa.String(length=32), nullable=False),
    sa.Column('routing_log', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['case_file_id'], ['case_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_case_file_id'), ['case_file_id'], unique=False)

    op.create_table('source_check_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_file_id', sa.Uuid(), nullable=False),
    sa.Column('source_name', sa.String(length=512), nullable=False),
    sa.Column('query_string', sa.Text(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checked_by', sa.String(length=256), nullable=False),
    sa.Column('result_hash', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['case_file_id'], ['case_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_check_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_check_logs_case_file_id'), ['case_file_id'], unique=False)

    op.create_table('subject_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_file_id', sa.Uuid(), nullable=False),
    sa.Column('subject_name', sa.String(length=512), nullable=False),
    sa.Column('subject_type', sa.String(length=64), nullable=False),
    sa.Column('bioguide_id', sa.String(length=32), nullable=True),
    sa.Column('state', sa.String(length=8), nullable=True),
    sa.Column('district', sa.String(length=16), nullable=True),
    sa.Column('office', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['case_file_id'], ['case_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subject_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subject_profiles_case_file_id'), ['case_file_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subject_profiles_case_file_id'))

    op.drop_table('subject_profiles')
    with op.batch_alter_table('source_check_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_check_logs_case_file_id'))

    op.drop_table('source_check_logs')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_case_file_id'))

    op.drop_table('signals')
    with op.batch_alter_table('evidence_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_entries_evidence_hash'))
        batch_op.drop_index(batch_op.f('ix_evidence_entries_case_file_id'))

    op.drop_table('evidence_entries')
    with op.batch_alter_table('case_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_snapshots_case_file_id'))

    op.drop_table('case_snapshots')
    with op.batch_alter_table('case_contributors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_contributors_case_file_id'))

    op.drop_table('case_contributors')
    with op.batch_alter_table('investigators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigators_handle'))

    op.drop_table('investigators')
    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_files_slug'))

    op.drop_table('case_files')
    with op.batch_alter_table('adapter_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adapter_cache_query_hash'))
        batch_op.drop_index(batch_op.f('ix_adapter_cache_adapter_name'))

    op.drop_table('adapter_cache')
    # ### end Alembic commands ###
